Repository agoel27/ai-job-portal, pull requests merged in 2025-03, with the labels that each got.

#12 sign in v2 attempt 1
  README.md
  backend/api/__pycache__/__init__.cpython-313.pyc
  backend/api/__pycache__/admin.cpython-313.pyc
  backend/api/__pycache__/apps.cpython-313.pyc
  backend/api/__pycache__/models.cpython-313.pyc
  backend/api/__pycache__/serializers.cpython-313.pyc
  backend/api/__pycache__/views.cpython-313.pyc
  backend/api/migrations/__pycache__/0001_initial.cpython-313.pyc
  backend/api/migrations/__pycache__/__init__.cpython-313.pyc
  backend/api/urls.py
  backend/api/views.py
  backend/backend/__pycache__/__init__.cpython-313.pyc
  backend/backend/__pycache__/settings.cpython-313.pyc
  backend/backend/__pycache__/urls.cpython-313.pyc
  backend/backend/__pycache__/wsgi.cpython-313.pyc
  backend/backend/settings.py
  backend/backend/urls.py
  backend/db.sqlite3
  backend/requirements.txt
  frontend/eslint.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/api.js
  frontend/src/components/Form.jsx
  frontend/src/components/GoogleLoginButton.jsx
  frontend/src/components/LoadingIndicator.jsx
  frontend/src/components/ProtectedRoute.jsx
  frontend/src/constants.js
  frontend/src/main.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/NotFound.jsx
  frontend/src/pages/Register.jsx
  frontend/src/styles/Form.css
  frontend/src/styles/Home.css
  frontend/src/styles/LoadingIndicator.css
  frontend/src/styles/Note.css
  frontend/vite.config.js
  package-lock.json
  package.json
Labels: ready for review

#17 Arieen17/login
  backend/.env
  frontend/public/AILogo.webp
  frontend/src/components/Form.jsx
  frontend/src/components/ProtectedRoute.jsx
  frontend/src/pages/Login.jsx
  frontend/src/styles/Form.css
Labels: ready for review

#39 added pages
  frontend/src/App.jsx
  frontend/src/pages/ApplicantCenter.jsx
  frontend/src/pages/ApplicantJobDetails.jsx
  frontend/src/pages/ApplicantJobPortal.jsx
  frontend/src/pages/NewJobApplicantInfo.jsx
  frontend/src/pages/NewJobDetails.jsx
  frontend/src/pages/NewJobFinalDetails.jsx
  frontend/src/pages/NewJobPreview.jsx
  frontend/src/pages/RecruiterCenter.jsx
  frontend/src/pages/SubmitResume.jsx
Labels: ready for review

#13 add logo to register page
  frontend/src/components/Form.jsx
  frontend/src/pages/Register.jsx
Labels: enhancement, ready for review

#14 add header to submit resume page
  frontend/src/main.jsx
  frontend/src/pages/SubmitResume.jsx
  frontend/vite.config.js
Labels: enhancement, ready for review

#15 added register header
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Form.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/Register.jsx
  frontend/src/styles/Form.css
Labels: enhancement

#38 New Post Title and Progress Bar
  frontend/src/components/new_job_post/Title.jsx
  frontend/src/components/new_job_post/new_job_details/Form.jsx
  frontend/src/components/new_job_post/progress_bar/CircleCheckComplete.jsx
  frontend/src/components/new_job_post/progress_bar/CircleCheckCurrent.jsx
  frontend/src/components/new_job_post/progress_bar/CircleCheckIncomplete.jsx
  frontend/src/components/new_job_post/progress_bar/ProgressBar.jsx
  frontend/src/pages/NewJobDetails.jsx
  frontend/src/styles/ProgressBar.css
Labels: ready for review

#37 Email Verification
  .gitignore
  README.md
  backend/api/migrations/0001_initial.py
  backend/api/migrations/__init__.py
  backend/api/models.py
  backend/api/serializers.py
  backend/api/utils/emails.py
  backend/api/views.py
  backend/backend/settings.py
  backend/backend/urls.py
  backend/db.sqlite3
  frontend/src/App.jsx
  frontend/src/components/Form.jsx
  frontend/src/pages/EmailSent.jsx
  frontend/src/pages/EmailVerify.jsx
  frontend/src/pages/Login.jsx
Labels: ready for review
